WINDOW_WIDTH = 1060
WINDOW_HEIGHT = 720

SORTING_SECTION_WIDTH = 660
SORTING_SECTION_HEIGHT = 660
SORTING_SECTION_MARGIN = (WINDOW_HEIGHT - SORTING_SECTION_HEIGHT) // 2

SORTING_INFO_TOP_DISPLAY_HEIGHT = 40

SORTING_VISUALISER_WIDTH = SORTING_SECTION_WIDTH - SORTING_SECTION_MARGIN * 3
SORTING_VISUALISER_HEIGHT = SORTING_SECTION_HEIGHT - SORTING_SECTION_MARGIN * 4 - SORTING_INFO_TOP_DISPLAY_HEIGHT # inner and outer margins

SORTING_VISUALISER_START_X = SORTING_SECTION_MARGIN * 2
SORTING_VISUALISER_START_Y = SORTING_SECTION_MARGIN * 4 + SORTING_INFO_TOP_DISPLAY_HEIGHT
SORTING_VISUAISER_MID_X = SORTING_SECTION_MARGIN * 2 + SORTING_VISUALISER_WIDTH // 2
SORTING_VISUALISER_END_X = SORTING_VISUALISER_START_X + SORTING_VISUALISER_WIDTH
SORTING_VISUALISER_END_Y = SORTING_VISUALISER_START_Y + SORTING_VISUALISER_HEIGHT

MENU_SECTION_WIDTH = WINDOW_WIDTH - SORTING_SECTION_WIDTH
MENU_SECTION_HEIGHT = WINDOW_HEIGHT
MENU_SECTION_START_X = WINDOW_WIDTH - MENU_SECTION_WIDTH
MENU_SECTION_MID_X = WINDOW_WIDTH - (MENU_SECTION_WIDTH // 2)

LIST_MIN = 1
LIST_MAX = 99

LIST_MIN_SIZE = 10
LIST_MAX_SIZE = 100
LIST_SIZE_INCREMENT = 10

MIN_SPEED = 10
MAX_SPEED = 120
LIST_SPEED_INCREMENT = 10